#pragma once

#include <string>

enum class TokenType {
	// The default
	unk,

	// Tokens recognized by the tokenizer
	key_struct,
	key_union,
	key_void,
	key_char,
	key_short,
	key_int,
	key_long,
	key_float,
	key_double,
	key_signed,
	key_unsigned,
	key_return,
	key_case,
	key_break,
	key_continue,
	key_default,
	key_do,
	key_else,
	key_enum,
	key_for,
	key_goto,
	key_if,
	key_switch,
	key_while,
	key_const,
	key_volatile,
	key_typedef,
	key_extern,
	key_static,
	key_auto,
	key_register,

	equals,
	add,
	sub,
	star,
	tilda,
	exclam,
	div,
	percent,
	ampersand,
	pipe,
	question,
	hat,
	period,
	comma,
	semi_colon,
	colon,
	less_than,
	greater_than,

	open_bracket,
	close_bracket,
	open_parenth,
	close_parenth,
	open_square_bracket,
	close_square_bracket,


	// Tokens recognized by the parser
	identifier,
	constant,
	string_literal,
	a_sizeof,
	ptr_op,
	inc_op,
	dec_op,
	left_op,
	right_op,
	le_op,
	ge_op,
	eq_op,
	ne_op,
	and_op,
	or_op,
	mul_assign,
	div_assign,
	mod_assign,
	add_assign,
	sub_assign,
	left_assign,
	right_assign,
	and_assign,
	xor_assign,
	or_assign,


	// char to void handled above
	primary_expression,
	postfix_expression,
	argument_expression_list,
	unary_expression,
	unary_operator,
	cast_expression,
	multiplicative_expression,
	additive_expression,
	shift_expression,
	relational_expression,
	equality_expression,
	and_expression,
	exclusive_or_expression,
	inclusive_or_expression,
	logical_and_expression,
	logical_or_expression,
	conditional_expression,
	assignment_expression,
	assignemnt_operator,
	expression,
	constant_expression,
	declaration,
	declaration_specifiers,
	init_declarator_list,
	init_declarator,
	storage_class_specifier,
	type_specifier,
	struct_or_union_specifier,
	struct_or_union,
	struct_declaration_list,
	struct_declaration,
	specifier_qualifier_list,
	struct_declarator_list,
	struct_declarator,
	enum_specifier,
	enumerator_list,
	enumerator,
	type_qualifier,
	declarator,
	direct_declarator,
	pointer,
	type_qualifier_list,
	parameter_type_list,
	parameter_list,
	parameter_declaration,
	identifier_list,
	type_name,
	abstract_declarator,
	direct_abstract_declarator,
	initializer,
	initializer_list,
	statement,
	labeled_statement,
	compound_statement,
	declaration_list,
	statement_list,
	expression_statement,
	selection_statement,
	iteration_statement,
	jump_statement,
	translation_unit,
	external_declaration,
	function_definition,

	last_token,
};

std::string token_to_string(TokenType token);
