// ret: 10

int my_fun()
{
    return 10;
}

// In earlier versions of the compiler it would generate an end label for each
// function that was the function name plus "_end". Which will break if you have
// two functions that have the same name, minus the prefix.
int my_fun_end()
{
    return 11;
}

// Static data also gets an autogenerated label, but since the funtion label
// also always has the postfix _end, there is no clash
int static_data()
{
    return 1;
}

// Also auto generated are "L" labels
int L1(int a)
{
    if (a) {
        return 10;
    } else {
        return 100;
    }
    return 2;
}

int main()
{
    return my_fun();
}
