name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get resources
      run: |
        cd cr-cc
        wget https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp
        mv catch.hpp cr-cc-test/catch.h

    - name: Build
      run: |
        cd cr-cc
        make
        
    - name: Run unit test
      run: |
        cd cr-cc
        ./test  --benchmark-no-analysis
        
    - name: Run build a compiler test
      run: |
        cd cr-cc
        git clone https://github.com/clayton-rogers/write_a_c_compiler.git
        cd write_a_c_compiler
        git checkout fix_for_non_x86_compiler
        ./test_compiler.sh ../cc 1 2     # add stages as compiler gets more complete
        
