name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CRSTDLIBPATH: ${{ github.workspace }}/cr-cc/stdlib

    steps:
    - uses: actions/checkout@v1
    - name: Get resources
      run: |
        cd cr-cc
        wget https://raw.githubusercontent.com/catchorg/Catch2/v2.x/single_include/catch2/catch.hpp
        mv catch.hpp cr-cc-test/catch.h

    - name: Build
      run: |
        cd cr-cc
        mkdir build
        cd build
        cmake ..
        make -j

    - name: Build stdlib
      run: |
        PATH=$(pwd)/cr-cc/build/cr-cc/:$PATH
        cd cr-cc/stdlib
        make

    - name: Run unit test
      run: |
        PATH=$(pwd)/cr-cc/build/cr-cc-test/:$PATH
        cd cr-cc
        cr-cc-test
        cr-cc-test "[bench]" --benchmark-no-analysis --benchmark-samples 25
        cr-cc-test "[long_bench]" --benchmark-no-analysis --benchmark-samples 5

    - name: Build and run test code
      run: |
        PATH=$(pwd)/cr-cc/build/cr-cc/:$PATH
        cd cr-cc/test_data
        ./build_and_run_test_code.sh
