name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get resources
      run: |
        cd cr-cc
        wget https://raw.githubusercontent.com/catchorg/Catch2/v2.x/single_include/catch2/catch.hpp
        mv catch.hpp cr-cc-test/catch.h

    - name: Build
      run: |
        cd cr-cc
        make
        mkdir build
        mv cc build/cr-cc
        mv test build/cr-cc-test

    - name: Build stdlib
      run: |
        cd cr-cc/stdlib
        PATH=../build:$PATH
        make

    - name: Run unit test
      run: |
        cd cr-cc
        ./build/cr-cc-test  "*,[.]" --benchmark-no-analysis

    - name: Build and run test code
      run: |
        cd cr-cc/test_data
        chmod 755 build_and_run_test_code.sh
        PATH=../../build:$PATH CRSTDLIBPATH=../../stdlib ./build_and_run_test_code.sh
