name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CRSTDLIBPATH: ${{ github.workspace }}/stdlib

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j

    - name: Build stdlib
      run: |
        PATH=$(pwd)/build/cr-cc/:$PATH
        cd stdlib
        make

    - name: Run unit test
      run: |
        PATH=$(pwd)/build/cr-cc-test/:$PATH
        cr-cc-test
        cr-cc-test "[bench]" --benchmark-no-analysis --benchmark-samples 25
        cr-cc-test "[long_bench]" --benchmark-no-analysis --benchmark-samples 5

    - name: Build and run test code
      run: |
        PATH=$(pwd)/build/cr-cc/:$PATH
        cd test_data
        ./build_and_run_test_code.sh
